export const DELETE_DATA_START = "DELETE_DATA_START";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL";

export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";

export const VIEW_DATA_START = "VIEW_DATA_START";
export const VIEW_DATA_SUCCESS = "VIEW_DATA_SUCCESS";
export const VIEW_DATA_FAIL = "VIEW_DATA_FAIL";

export const SAVE_DATA_SUCCESS = "SAVE_DATA_SUCCESS";
export const SAVE_DATA_FAIL = "SAVE_DATA_FAIL";

export const SEARCH_DATA = "SEARCH_DATA";
